### ISSUE TITLE
dartdoc fails on pub.dev

### ISSUE THREAD

**Issue by fujidaiti** [fujidaiti/smooth_sheets#23]
It appears that the API reference has not been generated for v0.2.0 on the [package site](https://pub.dev/packages/smooth_sheets/score).

```
OUT: Documenting smooth_sheets... Discovering libraries... Linking elements... Precaching local docs for 599456 elements... Initialized dartdoc with 738 libraries ERR: dartdoc 8.0.4 (/tmp/analyzerSSGLNB/pub-cache/global_packages/dartdoc/bin/dartdoc.dart-3.2.6.snapshot) failed: Bad state: No element #0 List.last (dart:core-patch/growable_array.dart:348:5) #1 AlertBlockSyntax.parseChildLines (package:markdown/src/block_syntaxes/alert_block_syntax.dart:54:35) #2 AlertBlockSyntax.parse (package:markdown/src/block_syntaxes/alert_block_syntax.dart:85:24) #3 BlockParser.parseLines (package:markdown/src/block_parser.dart:178:32) #4 MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:299:37) #5 Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:78:21) #6 Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:59:23) #7 Documentation.asHtml (package:dartdoc/src/model/documentation.dart:44:5) #8 Package.documentationAsHtml (package:dartdoc/src/model/package.dart:120:74) [15 more lines]
```

Maybe it failed while parsing GitHub-style alert blocks?

```
#2 AlertBlockSyntax.parse (package:markdown/src/block_syntaxes/alert_block_syntax.dart:85:24)
```

**Comment by fujidaiti** [comment]
- Pub.dev uses [dartdoc](https://pub.dev/packages/dartdoc) to generate documentation for a package on the site, and dartdoc uses [markdown](https://pub.dev/packages/markdown) to parse *`.md` files. 
- The [alert syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) from GitHub Flavored Markdown has been supported in [markdown v7.2.1](https://pub.dev/packages/markdown/changelog#721), which is included in dartdoc from [v8.0.5](https://github.com/dart-lang/dartdoc/blob/f152c0138bff8e4265a3459a6b08e4a83fe860b7/pubspec.yaml#L17).
- Unfortunately, pub.dev currently uses [dartdoc v8.0.4](https://github.com/dart-lang/pub-dev/blob/93e65bbf9f48827cce0df49f38cf0cb0de10f7b3/app/lib/shared/versions.dart#L79) and therefore cannot parse the alerts in a README.

I will wait until the next release to address this issue, hoping that pub.dev will be using v8.0.5 by then.
