### ISSUE TITLE
Clicking on the modal barrier during dragging will cause an error

### ISSUE THREAD

**Issue by huahua8893** [fujidaiti/smooth_sheets#54]
Great work and great doc, but I found a problem that click on the background page during dragging will cause an error, like this:

https://github.com/fujidaiti/smooth_sheets/assets/10332761/7af44d63-f9a9-497c-ab46-c0d27b607047

Use "[cupertino_modal_sheet.dart](https://github.com/fujidaiti/smooth_sheets/blob/main/cookbook/lib/tutorial/cupertino_modal_sheet.dart)" demo can see this

And I will submit another issue for a new feature request

**Comment by fujidaiti** [comment]
I tried to reproduce the problem and found that an unexpected pop event occurs when the barrier is tapped.

<details>
<summary>Error Log</summary>

```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Only valid value is 0: -1

When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _History.[] (package:flutter/src/widgets/navigator.dart:3474:18)
#2      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:5457:44)
#3      _SheetDismissibleState._handleDragStart (package:smooth_sheets/src/modal/modal_sheet.dart:249:29)
#4      _DragGestureRecognizer._checkStart.<anonymous closure> (package:smooth_sheets/src/internal/monodrag.dart:543:53)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315:24)
#6      _DragGestureRecognizer._checkStart (package:smooth_sheets/src/internal/monodrag.dart:543:7)
#7      _DragGestureRecognizer._checkDrag (package:smooth_sheets/src/internal/monodrag.dart:507:5)
#8      _DragGestureRecognizer.acceptGesture (package:smooth_sheets/src/internal/monodrag.dart:440:7)
#9      GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:281:12)
#10     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:239:9)
#11     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53:12)
#12     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:415:13)
#13     _DragGestureRecognizer.handleEvent (package:smooth_sheets/src/internal/monodrag.dart:421:13)
#14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
#22     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#23     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#26     _invoke1 (dart:ui/hooks.dart:328:13)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

Handler: "onStart"
Recognizer: _PullToDismissGestureRecognizer#804c6
    debugOwner: _SheetDismissibleState#e7785
    start behavior: start
════════════════════════════════════════════════════════════════════════════════
```
</details>

Probably I'll disable route poping during a pull-to-dismiss action.
